#!/usr/bin/env python3
"""
Post-processing script to fix pprldflex-config.js generated by cocopp.

This script fixes the filename paths in pprldflex-config.js to match the actual
files that exist, since cocopp may generate incorrect filename templates.

Usage:
    python fix_pprldflex_config.py <path_to_results_directory>
    
Example:
    python fix_pprldflex_config.py ppdata/exdata/results/cmaes_comparison_20251214_013258_121402h4434
"""

import os
import sys
import re
import json
from pathlib import Path
from typing import List, Dict, Set


def find_available_dimensions(results_dir: Path) -> List[int]:
    """Find which dimensions are actually available in the results."""
    dimensions = set()
    
    # Check function group files with dimension suffixes
    single_func_dir = results_dir / "pprldmany-single-functions"
    if single_func_dir.exists():
        for file in single_func_dir.glob("pprldmany_gr_*_*D.svg"):
            # Extract dimension from filename like pprldmany_gr_separ_02D.svg
            match = re.search(r'_(\d+)D\.svg$', file.name)
            if match:
                dimensions.add(int(match.group(1)))
    
    return sorted(list(dimensions))


def check_file_exists(results_dir: Path, filename: str) -> bool:
    """Check if a file exists relative to results_dir."""
    file_path = results_dir / filename
    return file_path.exists()


def fix_config_file(results_dir: Path) -> bool:
    """Fix the pprldflex-config.js file in the results directory."""
    config_file = results_dir / "pprldflex-config.js"
    
    if not config_file.exists():
        print(f"Error: {config_file} not found!")
        return False
    
    # Read the config file
    with open(config_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Find available dimensions
    available_dims = find_available_dimensions(results_dir)
    if not available_dims:
        print(f"Warning: No dimension-specific files found. Using default dimensions.")
        available_dims = [2, 5, 10, 20]
    
    print(f"Found available dimensions: {available_dims}")
    
    # Extract the config object using regex
    # Match from "const config = {" to the closing "}" (with or without semicolon)
    config_match = re.search(r'const config = (\{.*?\})\s*;?\s*$', content, re.DOTALL | re.MULTILINE)
    if not config_match:
        # Try matching without requiring end of file
        config_match = re.search(r'const config = (\{.*?\})', content, re.DOTALL)
        if not config_match:
            print("Error: Could not find config object in file!")
            return False
    
    # Parse the config (it's JavaScript, but we can extract it)
    config_str = config_match.group(1)
    
    # Fix dimensions
    dim_pattern = r'"dimensions":\s*\[[^\]]*\]'
    new_dims_str = f'"dimensions": {json.dumps(available_dims)}'
    config_str = re.sub(dim_pattern, new_dims_str, config_str)
    
    # Fix individual function filenames (remove dimension suffix template)
    # Pattern: "filename": "pprldmany-single-functions/pprldmany_f001_<0,2>D.svg"
    # Should be: "filename": "pprldmany-single-functions/pprldmany_f001.svg"
    func_pattern = r'("filename":\s*"pprldmany-single-functions/pprldmany_f\d+)_<0,2>D\.svg"'
    config_str = re.sub(func_pattern, r'\1.svg"', config_str)
    
    # Fix function group filenames (update to use gr_ prefix pattern)
    # Pattern: "filename": "pprldmany_<0,2>D_separ.svg"
    # Should be: "filename": "pprldmany-single-functions/pprldmany_gr_separ_<0,2>D.svg"
    group_mappings = {
        r'pprldmany_<0,2>D_separ\.svg"': 'pprldmany-single-functions/pprldmany_gr_separ_<0,2>D.svg"',
        r'pprldmany_<0,2>D_lcond\.svg"': 'pprldmany-single-functions/pprldmany_gr_lcond_<0,2>D.svg"',
        r'pprldmany_<0,2>D_hcond\.svg"': 'pprldmany-single-functions/pprldmany_gr_hcond_<0,2>D.svg"',
        r'pprldmany_<0,2>D_multi\.svg"': 'pprldmany-single-functions/pprldmany_gr_multi_<0,2>D.svg"',
        r'pprldmany_<0,2>D_mult2\.svg"': 'pprldmany-single-functions/pprldmany_gr_mult2_<0,2>D.svg"',
    }
    
    for old_pattern, new_path in group_mappings.items():
        # Find all occurrences and replace
        pattern = r'("filename":\s*")' + old_pattern
        replacement = r'\1' + new_path
        config_str = re.sub(pattern, replacement, config_str)
    
    # Remove "all" function group if it doesn't exist
    # Pattern: {"name": "all", "filename": "pprldmany_<0,2>D_noiselessall.svg"}
    noiseless_pattern = r',\s*\{\s*"name":\s*"all",\s*"filename":\s*"[^"]*noiselessall[^"]*"\s*\}'
    config_str = re.sub(noiseless_pattern, '', config_str)
    
    # Reconstruct the file content
    new_content = content[:config_match.start(1)] + config_str + content[config_match.end(1):]
    
    # Write back
    with open(config_file, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    print(f"[OK] Fixed {config_file}")
    return True


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python fix_pprldflex_config.py <path_to_results_directory>")
        print("\nExample:")
        print("  python fix_pprldflex_config.py ppdata/exdata/results/cmaes_comparison_20251214_013258_121402h4434")
        sys.exit(1)
    
    results_dir = Path(sys.argv[1])
    
    if not results_dir.exists():
        print(f"Error: Directory {results_dir} does not exist!")
        sys.exit(1)
    
    if not results_dir.is_dir():
        print(f"Error: {results_dir} is not a directory!")
        sys.exit(1)
    
    print(f"Fixing pprldflex-config.js in: {results_dir}")
    print("-" * 60)
    
    success = fix_config_file(results_dir)
    
    if success:
        print("-" * 60)
        print("[OK] Config file fixed successfully!")
        print("\nYou can now refresh pprldflex.html in your browser.")
    else:
        print("-" * 60)
        print("[ERROR] Failed to fix config file.")
        sys.exit(1)


if __name__ == "__main__":
    main()

